import 'dotenv/config'

import '@/commands/actives'
import '@/commands/add'
import '@/commands/balance'
import '@/commands/buy'
import '@/commands/claim'
import '@/commands/movers'
import '@/commands/news'
import '@/commands/portfolio'
import '@/commands/remove'
import '@/commands/sell'
import '@/commands/view'
import '@/commands/watchlist'
